# Generated by Django 4.0.4 on 2022-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tianyQbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='config',
            table='user',
        ),
    ]
